name: PIPELINE CI/CD
on:
  push:
    branches: ["main"]
  # Permite o disparo da pipeline manualmente
  workflow_dispatch:
  # Declaração dos Jobs
jobs:
  # Ambiente de CI
  PIPELINE-CI:
    # Qual o SO será utilizado neste ambiente
    runs-on: ubuntu-latest
    # Iniciando os Passos da atividade
    steps:
      # Utilizando a Action Checkout para buscar o código do repositório
      - name: "Obtendo o código fonte da aplicação"
        uses: actions/checkout@v4
      # Utilizando a Action de Login do Docker para armazenar a nova image no DockerHub
      - name: "Autenticando no Docker Hub"
        uses: docker/login-action@v3
        with:
          # Utilizando o vault de secredo do GitHub Actions dados sensíveis
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Gerando o Build e Push da imagem"
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-first-pipeline:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-first-pipeline:latest
  
  PIPELINE-CD:
    runs-on: ubuntu-latest
    needs: [PIPELINE-CI]
    steps:
      - name: "Obtendo o código do manifesto do Kubernetes"
        uses: actions/checkout@v4
      # Configuração do Kubeconfig - Cluster Kubernetes
      # Obtendo a configuração do Cluster Kubernetes no Azure com o comando # az aks get-credentials -n kubernetes_devops -g DEVOPS-KUBERNETES
      - name: "Configurando o contexto do Kubernetes no arquivo kubeconfig"
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.CLUSTER_KUBERNETES_KUBECONFIG }}
      - name: "Execução do Manifesto Kubernetes"
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: ${{ secrets.DOCKERHUB_USERNAME }}/devops-first-pipeline:v${{ github.run_number }}
         